FROM python:3.8-slim-bullseye

COPY . /app

WORKDIR /app

ARG SEC_KEY_NEW
ARG ALGO_TYPE
ARG DB_URL_NEW
ARG DB_NAME_NEW
ARG USR_COL_NEW
ARG EMBED_COL_NEW

ENV SECRET_KEY=$SEC_KEY_NEW
ENV ALGORITHM=$ALGO_TYPE
ENV MONGODB_URL_KEY=$DB_URL_NEW
ENV DATABASE_NAME=$DB_NAME_NEW
ENV USER_COLLECTION_NAME=$USR_COL_NEW
ENV EMBEDDING_COLLECTION_NAME=$EMBED_COL_NEW

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y && pip install -r requirements.txt

CMD ["python", "app.py"]
