name: Docker Build and Push

on:
  push:
    branches:
      - azure-vm-deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/face_auth:latest
        build-args: |
          SECRET_CODE_ENV=${{ secrets.SECRET_CODE_ENV }}
          ENCRYPTION_ALGO_ENV=${{ secrets.ENCRYPTION_ALGO_ENV }}
          DB_USER_ENV=${{ secrets.DB_USER_ENV }}
          DB_PASSWORD_ENV=${{ secrets.DB_PASSWORD_ENV }}
          DB_TITLE_ENV=${{ secrets.DB_TITLE_ENV }}
          USER_TABLE_ENV=${{ secrets.USER_TABLE_ENV }}
          EMBED_TABLE_ENV=${{ secrets.EMBED_TABLE_ENV }}

    - name: Deploy to Azure VM
      run: |
        echo "${{ secrets.AZURE_VM_SSH_KEY }}" > /tmp/azure_vm_ssh_key
        chmod 600 /tmp/azure_vm_ssh_key
        ssh -o StrictHostKeyChecking=no -i /tmp/azure_vm_ssh_key ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} <<-EOF
        docker pull ${{ secrets.DOCKER_USERNAME }}/face_auth:latest
        docker stop face_auth || true
        docker rm face_auth || true
        docker run -d -p 8080:8080 --name face_auth ${{ secrets.DOCKER_USERNAME }}/face_auth:latest
        EOF
