name: Docker Build and Push

on:
  push:
    branches:
      - azure-vm-deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/face_auth:latest
        build-args: |
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          ALGORITHM=${{ secrets.ALGORITHM }}
          MONGODB_URL_KEY=${{ secrets.MONGODB_URL_KEY }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          USER_COLLECTION_NAME=${{ secrets.USER_COLLECTION_NAME }}
          EMBEDDING_COLLECTION_NAME=${{ secrets.EMBEDDING_COLLECTION_NAME }}

    - name: Deploy to Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.AZURE_VM_SSH_KEY }} ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
        docker pull ${{ secrets.DOCKER_USERNAME }}/face_auth:latest
        docker stop face_auth || true
        docker rm face_auth || true
        docker run -d -p 8000:8000 --name face_auth ${{ secrets.DOCKER_USERNAME }}/face_auth:latest
        EOF
